if(PBASIC_LIBRARY_CONFIGURED)
    return()
endif(PBASIC_LIBRARY_CONFIGURED)

set(PBASIC_LIBRARY_CONFIGURED true)

set(PBASIC_LIB_TARGET "pBasic")
set(PASIC_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/pBasicLib/include")
